#############################################################################
# Generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#  Dec 07, 2020 10:25:33 AM CST  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background #004040 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1264x640
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 1
    wm maxsize $top 2810 881
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Limpiando Texto 4.3"
    vTcl:DefineAlias "$top" "FRMLimpiandoTexto" vTcl:Toplevel:WidgetProc "" 1
    vTcl::widgets::ttk::scrolledtext::CreateCmd $top.scr43 \
        -background $vTcl(actual_gui_bg) -height 75 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 125 
    vTcl:DefineAlias "$top.scr43" "txtCajaTexto" vTcl:WidgetProc "FRMLimpiandoTexto" 1

    $top.scr43.01 configure -background white \
        -font font9 \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -wrap none
    label $top.lab44 \
        -activebackground #f9f9f9 -activeforeground black -background #004040 \
        -disabledforeground #a3a3a3 \
        -font {-family {Arial} -size 28 -weight bold} -foreground #ff8000 \
        -highlightbackground #ff8000 -highlightcolor black \
        -text {Limpando Texto 4.3} 
    vTcl:DefineAlias "$top.lab44" "Label1" vTcl:WidgetProc "FRMLimpiandoTexto" 1
    entry $top.ent45 \
        -background white -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_fixed_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$top.ent45" "txbTextoAModificar" vTcl:WidgetProc "FRMLimpiandoTexto" 1
    entry $top.ent47 \
        -background white -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_fixed_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$top.ent47" "txbDireccionArchivo" vTcl:WidgetProc "FRMLimpiandoTexto" 1
    button $top.but48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #00ff00 -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Abrir -width 59 
    vTcl:DefineAlias "$top.but48" "btnAbrir" vTcl:WidgetProc "FRMLimpiandoTexto" 1
    button $top.but50 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffff00 -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Proceso -width 59 
    vTcl:DefineAlias "$top.but50" "btnProceso" vTcl:WidgetProc "FRMLimpiandoTexto" 1
    button $top.but51 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #0080ff -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Guardar -width 59 
    vTcl:DefineAlias "$top.but51" "btnGuardar" vTcl:WidgetProc "FRMLimpiandoTexto" 1
    button $top.but53 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ff0000 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor #ff8080 \
        -pady 0 -text Salir -width 59 
    vTcl:DefineAlias "$top.but53" "btnSalir" vTcl:WidgetProc "FRMLimpiandoTexto" 1
    button $top.but54 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ff8000 -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text + 
    vTcl:DefineAlias "$top.but54" "Button1" vTcl:WidgetProc "FRMLimpiandoTexto" 1
    entry $top.ent55 \
        -background white -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_fixed_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$top.ent55" "txbTextoModificado" vTcl:WidgetProc "FRMLimpiandoTexto" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.scr43 \
        -in $top -x 10 -y 60 -width 1241 -relwidth 0 -height 481 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab44 \
        -in $top -x 420 -y 10 -anchor nw -bordermode ignore 
    place $top.ent45 \
        -in $top -x 10 -y 550 -width 594 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent47 \
        -in $top -x 10 -y 580 -width 1034 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but48 \
        -in $top -x 1056 -y 580 -width 67 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but50 \
        -in $top -x 1130 -y 580 -width 63 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but51 \
        -in $top -x 1200 -y 580 -width 59 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but53 \
        -in $top -x 1200 -y 610 -width 57 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but54 \
        -in $top -x 1235 -y 550 -width 19 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.ent55 \
        -in $top -x 613 -y 550 -width 614 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

